### ISSUE TITLE
Could you split this image into 2, one with MinGW and CMake, another one with third-party libs

### ISSUE THREAD

**Issue by KOLANICH** [mdimura/docker-mingw-qt5#3]

**Comment by mdimura** [comment]
Yes, it is pending for quite some time, did not have time to do that. Maybe I'll get to this in February. Pull request is welcome as well.

**Comment by mdimura** [comment]
The issue is resolved now, one can use `burningdaylight/docker-mingw-arch:base` which contains a bare minimum of `mingw-` tools.

**Comment by KOLANICH** [comment]
Thanks. BTW https://gitlab.com/KOLANICH-subgroups/docker-images/ and https://gitlab.com/KOLANICH-subgroups/packages/cpp_build_tools and https://gitlab.com/KOLANICH-subgroups/packages/CMake_deb , but it is all for Debian.
